### ISSUE TITLE
Display Qaris

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/qurandl#14]
create a page for **displaying all Qaris**. it should contain a `table` for listing, `live search box` and we should be able to sort by clicking on table headers. also `pagination` and `item per page` limitation options are required.

# 📝 TODO:
- [x] Create a static file for Qaris in `public` directory and write your codes there
- [x] Add data table library and its dependencies (for searching, pagination and sorting table)
- [x] Add delete confirmation modal for deleting a Qari
- [x] Style data table options for `bs5` (pagination, select option, header columns and empty state for not found record)

# TABLE HEADER
here's items which need to be displayed in table:
- Row
- Qari's name
- Sourahs count
- Views
- Action buttons (Edit, Delete and Show)

# 👍 HELPER:
1. Use DataTable js library (depends on JQuery) or use another kind of library
2. Use bootstrap modal for confirmation:
```html
<div class="modal show" id="defaultModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">حذف قاری</h5>
            </div>
            <div class="modal-body">مطمئنید می&zwnj;خواهید قاری مورد نظر حذف شود؟</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light">خیر، منصرف شدم</button>
                <a href="#" class="btn btn-danger">بله، حذف کن</a>
            </div>
        </div>
    </div>
</div>
```

Jazakallahu Khayraa @AbdollahAshrafi 🙏
